02 model spec
runteq/sample_app_for_rspec pull request #40
Opened 2020-11-20 09:31 UTC by terakura-aina

■概要■
タスクモデルのバリデーションに関するテストを作成しました。
テストデータの作成にはFactoryBotを使用しています。

■確認方法■
バリデーションエラーの発生と、エラーメッセージの内容を確認してください。

■修正内容について■

9ed5c48で、解答と照らし合わせながら修正を行いました。
` config.include FactoryBot::Syntax::Methods`
この表記が何をしてくれるのかを知らなかったため、下記ブログで意味を調べました。
https://qiita.com/Ushinji/items/522ed01c9c14b680222c

意味としてはfactorybotメソッドを使用するときに`factorybot`の記述を省略できるようになる、とのことだったので、configに導入、合わせて該当コードを修正しました。

`expect(task_without_title.errors[:title]).to eq ["can't be blank"]`
↑解答の`eq`とその前に自分で記述していた`include`の違いについて

回答を見る前は`eq`の部分を`include`と記述しており、意味が違うのか調べてみました。
https://shinkufencer.hateblo.jp/entry/2019/06/26/233000

[![Image from Gyazo](https://i.gyazo.com/04b342c2b0e7b8bb1eb73282ab0bec03.png)](https://gyazo.com/04b342c2b0e7b8bb1eb73282ab0bec03)

順番を気にするか気にしないかの違いなのかと解釈したのですが、今回の場合はどちらでも良かったのでしょうか？

2020-11-20 09:34 UTC, yuji91 commented on spec/factories/tasks.rb
> +    status { "todo" }
enumの値は文字列のStringではなく、Symbol形式で記載した方が良いですね。ただの文字列を登録できるカラムでなく、enumで定義されているカラムであることを明示できます。
```suggestion
    status { :todo }
```

2020-11-20 09:39 UTC, yuji91 requested changes
> 今回の場合はどちらでも良かったのでしょうか？

eqの方がincludeよりもより厳密な確認となります。
そのため、テスト対象のモデルクラスにバリデーションが増えることが想定される場合は`include`で記載しないと`errors`オブジェクトの配列に含まれるエラーメッセージが増える可能性があるため、既存のテストケースがエラーになる場合があるかと思います。

今回はそのような確認対象の配列から取得される値が変化することが想定されないので、より厳密な`eq`を使う形で良いかと思います。

この辺りは細かい点になるので、参画した現場の記法を見て合わせるという形で良いかと思います。
`eq`の方がより厳密な確認をしているということだけ抑えておいてください。

2020-11-20 17:18 UTC, yuji91 commented on spec/factories/tasks.rb
> +    title { :test }
titleまでSymbolで記載する必要はないと思います！
一応この状態でテストが通るかもご確認ください。

2020-11-20 17:18 UTC, yuji91 requested changes
1点コメントしました。また、修正が完了した場合はslackで再度確認依頼をしてください。（修正に気づけないため）

2020-11-21 08:21 UTC, terakura-aina commented
21c5aab4bd3773e21d562d05b7e848fb796942ff
にてご指摘いただいたfactorybotの内容を修正しました。

eq、includeについての解説もありがとうございます。
なんとなく理解できました。

titleもSymbolでテストが通るか確認したところ、問題なく通りましたが、こちらは再度修正しました。

確認依頼について、作業途中で用ができてしまったため、slackでは後ほどお伝えしようとしていたところでした！
ですが気づいてくださりコメントまでいただき、ありがとうございます。

2020-11-21 08:42 UTC, yuji91 approved these changes

2020-11-23 06:21 UTC, yuji91 commented
マージ元のブランチが誤っていたため、クローズします。

2020-11-23 06:21 UTC, closed without merging